In [3]:
import numpy as np

In [4]:
arr = np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
arr_ones = np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
const = np.full(1,9)
const

array([9])

In [9]:
const_arr = np.full(3, 10)

In [10]:
const_arr

array([10, 10, 10])

In [11]:
const_arr = np.full(10,3)

In [13]:
const_arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [17]:
pl = [1,2,3]
arr = np.array(pl)

In [18]:
arr

array([1, 2, 3])

In [25]:
np.arange(1,10,10)

array([1])

In [26]:
rang_arr = np.arange(10)

In [27]:
rang_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
linspace_arr = np.linspace(1,10,11)

In [36]:
linspace_arr

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [41]:
zero_matrices = np.zeros((5,2))

In [42]:
zero_matrices

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
ones_matrices = np.ones((5,2))

In [44]:
ones_matrices

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
const_matrices = np.full((2,2), 3)

In [56]:
const_matrices

array([[3, 3],
       [3, 3]])

In [58]:
ml_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
ml_list_arr = np.array(ml_list)

In [59]:
ml_list_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
ml_list_arr[1,2]

np.int64(6)

In [66]:
ml_list_arr[:,0]

array([1, 4, 7])

In [73]:
np.random.seed(2)
rand_arr = np.random.rand(5,2)
rand_arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [74]:
normal_distribution = np.random.rand(2,5)

In [76]:
normal_distribution

array([[0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548]])

In [78]:
np.random.randint(low=0, high=100, size=(2,5))

array([[68, 46, 70, 95, 83],
       [31, 66, 80, 52, 76]])

In [79]:
arr

array([1, 2, 3])

In [80]:
arr + 1

array([2, 3, 4])

In [85]:
arr_mul = arr ** 2

In [88]:
arr_mul   - arr

array([0, 2, 6])

In [93]:
ml_list_arr, arr_mul

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([1, 4, 9]))

In [102]:
 ml = ml_list_arr + arr_mul

In [94]:
arr_mul > 2

array([False,  True,  True])

In [95]:
filtered = [arr_mul>2]

In [96]:
filtered

[array([False,  True,  True])]

In [103]:
only_10s = ml > 9

In [104]:
only_10s

array([[False, False,  True],
       [False, False,  True],
       [False,  True,  True]])

In [111]:
print (ml)
ml.min()

[[ 2  6 12]
 [ 5  9 15]
 [ 8 12 18]]


np.int64(2)

In [108]:
ml.max()

np.int64(18)

In [113]:
ml.sum()

np.int64(87)

In [115]:
ml.mean()

np.float64(9.666666666666666)

In [117]:
ml.std()

np.float64(4.784233364802441)

In [118]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [119]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [120]:
u+v

array([3, 4, 5, 8])

In [121]:
u*v

array([ 2,  0,  0, 12])

In [127]:
u.shape[0]

4

In [129]:
v.shape[0]

4

In [130]:
def vector_vector_mul(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result = result + u[i] * v[i]

    return result

In [133]:
vector_vector_mul(u,v)

np.float64(14.0)

In [134]:
u.dot(v)

np.int64(14)

In [140]:
m = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],
])

In [141]:
m

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [145]:
u.shape

(4,)

array([[ 4, 16, 25, 36],
       [ 2,  8,  5, 12],
       [ 6,  4, 10,  6]])

In [151]:
m.dot(u)



array([81, 27, 26])

In [152]:
m.shape

(3, 4)

In [157]:
def matrix_vector_mul(U, v):
    assert U.shape[1] == v.shape[0]

    rows = U.shape[0]
    results = np.zeros(rows)

    for i in range (rows):
        results[i] = vector_vector_mul(U[i], v)
    return results

In [159]:
matrix_vector_mul(m,v)

array([14.,  5.,  5.])

In [160]:
m.dot(v)

array([14,  5,  5])

In [166]:
V = np.array([
     [1,1,2],
    [0, .5,1],
    [0,2,1],
    [2,1,0]
    ])
V.shape


(4, 3)

In [167]:
V[:,0]

array([1., 0., 0., 2.])

In [163]:
np.zeros((4,3))
        
        

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [171]:
def matrix_matrix_mul(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    results = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_mul(U,vi)
        results[:, i] = Uvi
    return results

In [177]:
m

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [178]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [176]:
matrix_matrix_mul(m, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [174]:
m.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [179]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [181]:
I.dot(m)

array([[2., 4., 5., 6.],
       [1., 2., 1., 2.],
       [3., 1., 2., 1.]])

In [183]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])